### ISSUE TITLE
We need content!

### ISSUE THREAD

**Issue by mUtterberg** [CLEPyLadies/pyladies-official#3]
I posted the content from our ruby-based site as “Archived-Site” or something. I would love to be ale to delete that eventually and have the landing page be community-contributed blog posts. One option is to move that post as-is to the “pages” folder as our “About” page, but it might be beneficial to break it up into multiple pages first.

**Comment by CLEPyLadies** [comment]
Note: All content must have a line telling Pelican what the title should be. Omitting this information will break the Travis-CI build on your pull request, so we can't accept any PRs without this info!

Title: {{ title }}

**Comment by mUtterberg** [comment]
Closing this issue as we now have issues broken out into calls for specific content items.
